language: node_js
# Once openjdk/oraclejdk dependencies are resolved, change to dist: xenial
dist: trusty
notifications:
  email: false
node_js:
  - 8
  - 10
  - 12
matrix:
  fast_finish: true
env:
  matrix:
    - ES_VERSION=5.6.12
jdk:
  - oraclejdk8
install:
  - mkdir /tmp/elasticsearch
  - ./scripts/setup_ci.sh
  - npm i
script:
  - npm run travis
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - npm i -g npm
before_script:
  - sleep 10
  - curl http://127.0.0.1:9200/
  - ./bin/create_index
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      node_js: 12
      script: curl "https://raw.githubusercontent.com/pelias/ci-tools/master/semantic-release.sh" | bash -
      if: (branch = master) AND ( type = push )
